routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/home', 'HomeController@index')->name('home');
Route::get('/test', 'TestController@index')->name('test');
Route::group(['middleware' => 'auth'], function () {
    Route::post('/comment', 'CommentController@comment')->name('comment');
    Route::post('/comment/reply', 'CommentController@reply')->name('reply');
    Route::post('/file/upload', 'FileController@upload')->name('file.upload');
    Route::any('/ueditor', 'UeditorController@server')->name('ueditor');
});
Route::group(['middleware' => ['nav','category']], function () {

    Auth::routes();
    Route::get('/', 'IndexController@index');
    Route::get('/category/{slug?}', 'CategoryController@articles')->name('category-articles');
    Route::resource('article', 'ArticleController');
    Route::get('/user/profile/{id}', 'UserController@profile')->name('user.profile');
    Route::get('/user/{id}/articles', 'UserController@articles')->name('user.articles');
    Route::get('/user/{id}/edit', 'UserController@edit')->name('user.edit')->middleware('auth');
    Route::put('/user/{id}', 'UserController@update')->name('user.update')->middleware('auth');;
});

Route::get('/comment/lists/{article_id?}', 'CommentController@lists')->name('comment_lists');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public static function get_nick($id){
        $user                           = static :: where('id',$id)->first();
        if($user){
            return $user->name;
        }
    }

    public static function getByNick($nick){
        return static :: where('name',$nick)->first();
    }

    public function getAvatarAttribute($avatar){
        return get_image_url($avatar);
    }
}

app/Http/Controllers/UserController.php
<?php
/**
 * Author: XiaoFei Zhai
 * Date: 2018/2/3
 * Time: 9:38
 */

namespace App\Http\Controllers;


use App\Http\Requests\UpdateUserPut;
use App\Models\Article;
use App\User;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    public function profile($id){
        $user                               =   User::where(['id'=>$id])->first();
        $data['user']                       =   $user;
        $data['articles']                   =   Article::getByAuthor($id);
        $data['title']                      =   $user->name.' 个人中心';
        return view('user.profile',$data);

    }

    public function articles($id){
        $user                               =   User::where(['id'=>$id])->first();
        $data['user']                       =   $user;
        $data['articles']                   =   Article::where(['status'=>1,'author_id'=>$id])->orderBy('updated_at','desc')->paginate(20);
        $data['title']                      =   $user->name.' 全部文章';
        return view('user.articles',$data);
    }

    public function edit($id){

        $data['user']                       =   Auth::user();
        $data['title']                      =   '编辑个人资料';
        return view('user.edit',$data);
    }

    public function update(UpdateUserPut $request){
        $user                               =   Auth::user();
        if($request->email!=$user->email){
            $user->email                    =   $request->email;
        }
        if($request->nick != $user->nick){
            $user->nick                    =   $request->nick;
        }
        if($request->gender != $user->gender){
            $user->nick                    =   $request->nick;
        }
        if($request->introduction != $user->introduction){
            $user->introduction                    =   $request->introduction;
        }
        if($request->signature != $user->signature){
            $user->signature                    =   $request->signature;
        }
        if($request->gender != $user->gender){
            $user->gender                    =   $request->gender;
        }
        if(get_image_url($request->avatar) != $user->avatar){
            $user->avatar                    =   $request->avatar;
        }
        $user->save();
        return back();
    }
}

resources/views/user/articles.blade.php
@extends('layouts.default')
@section('body')
    <div class="users-show  row">
        <div class="col-md-3">
            <div class="box">
                <div class="padding-sm user-basic-info">
                    <div style="">
                        <div class="media">
                            <div class="media-left">
                                <div class="image">
                                    <img class="media-object avatar-112 avatar img-thumbnail"
                                         src="{{avatar($user->avatar)}}">
                                </div>
                            </div>
                            <div class="media-body">
                                <h3 class="media-heading">
                                    {{$user->name}}
                                </h3>
                                <div class="item">
                                    <svg width="14" height="16" viewBox="0 0 14 14" class="Icon Icon--male"
                                         aria-hidden="true"
                                         style="height: 16px; width: 14px;fill:#9fadc7;top: 2px;position: relative;">
                                        <title></title>
                                    </svg>
                                </div>
                                <div class="item number">
                                    注册于 <span class="timeago">{{ local_time_format($user->created_at)}}</span>
                                </div>

                                <div class="item number">
                                    活跃于 <span class="timeago">10小时前</span>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>

            </div>

        </div>
        <div class="main-col col-md-9 left-col">
            <div class="box text-center">A Life-long learner.</div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    文章
                </div>
                <div class="panel-body">
                    <ul class="list-group">
                        @if(!empty($articles))
                            @foreach($articles as $article)
                                <li class="list-group-item">
                                    <a href="{{route('article.show',['id'=>$article->id])}}" title="{{$article->title}}">
                                        {{$article->title}}
                                    </a>
                                    <span class="meta">
                                        <span> ⋅ </span>
                                        {{$article->comments}}
                                        <span> ⋅ </span>
                                        <span class="timeago">{{local_time_format($article->updated_at)}}</span>
                                  </span>
                                    @if(Auth::id()==$article->author_id)
                                        <a class="btn btn-success btn-sm pull-right" href="{{route('article.edit',['id'=>$article->id])}}">编辑</a>
                                    @endif
                                </li>
                                @endforeach
                        @endif
                    </ul>
                    <div class="pull-right add-padding-vertically">
                        {{$articles->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.default')
@section('body')
    <div class="users-show">

        <div class="col-md-3 main-col">
            <div class="box">
                <div class="padding-md ">
                    <div class="list-group text-center">
                        <a href="{{route('user.edit',['id'=>Auth::user()->id])}}" class="list-group-item active">
                            <i class="text-md iconfont icon-listalt" aria-hidden="true"></i>
                            &nbsp;个人信息
                        </a>
                        <a href="" class="list-group-item ">
                            <i class="text-md iconfont icon-22BELL" aria-hidden="true"></i>
                            &nbsp;消息通知
                        </a>

                        <a href="" class="list-group-item ">
                            <i class="text-md iconfont icon-lock" aria-hidden="true"></i>
                            &nbsp;修改密码
                        </a>
                    </div>
                </div>

            </div>
        </div>

        <div class="col-md-9  left-col ">

            <div class="panel panel-default padding-md">

                <div class="panel-body ">

                    <h2><i class="iconfont icon-setting" aria-hidden="true"></i> 编辑个人资料</h2>
                    <hr>


                    <form class="form-horizontal" method="POST" action="{{route('user.update',['id'=>Auth::user()->id])}}"
                          accept-charset="UTF-8" enctype="multipart/form-data">
                        <input name="_method" value="PUT" type="hidden">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="" class="col-sm-2 control-label">用户名</label>
                            <div class="col-sm-6">
                                <input class="form-control" disabled value="{{Auth::user()->name}}" type="text">
                            </div>

                            <div class="col-sm-4 help-block">

                            </div>
                        </div>
                        <div class="form-group">
                            <label for="" class="col-sm-2 control-label">昵称</label>
                            <div class="col-sm-6">
                                <input class="form-control" name="nick" value="{{Auth::user()->nick}}" type="text">
                            </div>

                            <div class="col-sm-4 help-block">
                                取个个性的昵称
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="" class="col-sm-2 control-label">头像</label>
                            <div class="col-sm-6">
                                @component('component.picture_upload',['path'=> !empty(Auth::user()->avatar) ? Auth::user()->avatar : '','name'=>'avatar'])
                                @endcomponent
                            </div>

                            <div class="col-sm-4 help-block">

                            </div>
                        </div>
                        <div class="form-group">
                            <label for="" class="col-sm-2 control-label">性别</label>
                            <div class="col-sm-6">
                                <select class="form-control" id="gender" name="gender">
                                    <option value="unselected" selected="">未选择</option>
                                    <option value="male">男</option>
                                    <option value="female">女</option>
                                </select>
                                <script>
                                    $("#gender option[value={{Auth::user()->gender}}]").attr("selected", "selected");
                                </script>
                            </div>

                            <div class="col-sm-4 help-block"></div>
                        </div>

                        <div class="form-group">
                            <label for="" class="col-sm-2 control-label">邮 箱</label>
                            <div class="col-sm-6">
                                <input class="form-control" name="email" value="{{Auth::user()->email}}" type="text">
                            </div>
                            <div class="col-sm-4 help-block">
                                如：name@website.com
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="" class="col-sm-2 control-label">个人简介</label>
                            <div class="col-sm-6">
                                <textarea class="form-control" rows="3" name="introduction" cols="50"
                                          style="overflow: hidden; overflow-wrap: break-word; resize: horizontal; height: 121px;"></textarea>
                            </div>
                            <div class="col-sm-4 help-block">
                                请一句话介绍你自己，大部分情况下会在你的头像和名字旁边显示
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="" class="col-sm-2 control-label">个性签名</label>
                            <div class="col-sm-6">
                                <textarea class="form-control" rows="3" name="signature" cols="50"
                                          style="overflow: hidden; overflow-wrap: break-word; resize: horizontal; height: 121px;"></textarea>
                            </div>
                            <div class="col-sm-4 help-block">
                                个性签名，会拼接在每一个你发表过的文章内容后面。
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-6">
                                <input class="btn btn-primary" id="user-edit-submit" value="应用修改" type="submit">
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>


    </div>
@endsection

resources/views/user/profile.blade.php
@extends('layouts.default')
@section('body')
    <div class="users-show  row">
        <div class="col-md-3">
            <div class="box">
                <div class="padding-sm user-basic-info">
                    <div style="">
                        <div class="media">
                            <div class="media-left">
                                <div class="image">
                                    <img class="media-object avatar-112 avatar img-thumbnail"
                                         src="{{avatar($user->avatar)}}">
                                </div>
                            </div>
                            <div class="media-body">
                                <h3 class="media-heading">
                                    {{$user->name}}
                                </h3>
                                <div class="item">
                                    <svg width="14" height="16" viewBox="0 0 14 14" class="Icon Icon--male"
                                         aria-hidden="true"
                                         style="height: 16px; width: 14px;fill:#9fadc7;top: 2px;position: relative;">
                                        <title></title>
                                    </svg>
                                </div>
                                <div class="item number">
                                    注册于 <span class="timeago">{{ local_time_format($user->created_at)}}</span>
                                </div>

                                <div class="item number">
                                    活跃于 <span class="timeago">10小时前</span>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>

            </div>

        </div>
        <div class="main-col col-md-9 left-col">
            <div class="box text-center">A Life-long learner.</div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    文章
                </div>
                <div class="panel-body">
                    <ul class="list-group">
                        @if(!empty($articles))
                            @foreach($articles as $article)
                                <li class="list-group-item">
                                    <a href="{{route('article.show',['id'=>$article->id])}}" title="{{$article->title}}">
                                        {{$article->title}}
                                    </a>
                                    <span class="meta">
                                        <span> ⋅ </span>
                                        {{$article->comments}}
                                        <span> ⋅ </span>
                                        <span class="timeago">{{local_time_format($article->updated_at)}}</span>
                                  </span>
                                    @if(Auth::id()==$article->author_id)
                                        <a class="btn btn-success btn-sm pull-right" href="{{route('article.edit',['id'=>$article->id])}}">编辑</a>
                                    @endif
                                </li>
                                @endforeach
                        @endif
                    </ul>
                    <div class="panel-footer" style="margin-top: 10px">
                        <a href="{{route('user.articles',['id'=>$user->id])}}" class="btn btn-default btn-sm">
                            所有文章
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection